### ISSUE TITLE
Updating framework

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/bare-app#9]
@LuckyCyborg I was playing with cakephp and I updated cake ver 3.2 to 3.3.3 in composer.   That is all I had to do and all still worked.  

Perhaps in nova 4 once all is stable is it possible to move some of the stuff that will always be in config\app to system?  So the only necessary update will be a composer update.  Get all the other (stuff not in vendor and system) to a point where it don't change, then only changes would be vendor and system.  

I thought that was neat to update cakephp with just a composer update.

**Comment by LuckyCyborg** [comment]
Also the CakePHP (or Laravel) configuration should be double checked on update. Probably you made minimal changes on configuration, if it worked out of box after going 3.2 -> 3.3.3.
